[2024-09-25T09:24:34.490+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:24:33.465781+00:00 [queued]>
[2024-09-25T09:24:34.495+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:24:33.465781+00:00 [queued]>
[2024-09-25T09:24:34.495+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2024-09-25T09:24:34.502+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_paginated_api_data> on 2024-09-25 09:24:33.465781+00:00
[2024-09-25T09:24:34.506+0000] {standard_task_runner.py:57} INFO - Started process 1045 to run task
[2024-09-25T09:24:34.510+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Batch_api_to_csv_with_dynamic_dates', 'fetch_paginated_api_data', 'manual__2024-09-25T09:24:33.465781+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/common_authentication_data_pipeline.py', '--cfg-path', '/tmp/tmp01zojo1z']
[2024-09-25T09:24:34.514+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask fetch_paginated_api_data
[2024-09-25T09:24:34.552+0000] {task_command.py:410} INFO - Running <TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:24:33.465781+00:00 [running]> on host fe5dec6acfed
[2024-09-25T09:24:34.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Batch_api_to_csv_with_dynamic_dates' AIRFLOW_CTX_TASK_ID='fetch_paginated_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T09:24:33.465781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T09:24:33.465781+00:00'
[2024-09-25T09:24:34.752+0000] {logging_mixin.py:150} INFO - Start Datsssssssssssssssssssssse: 2024-09-25 09:24:34.752870
[2024-09-25T09:24:34.753+0000] {logging_mixin.py:150} INFO - Start Date: 2024-09-24 01:00:00.000, End Date: 2024-09-25 01:00:00.000
[2024-09-25T09:24:34.934+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/common_authentication_data_pipeline.py", line 76, in fetch_data_and_save
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://34.124.138.144:8000/api/common/authentication
[2024-09-25T09:24:34.946+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Batch_api_to_csv_with_dynamic_dates, task_id=fetch_paginated_api_data, execution_date=20240925T092433, start_date=20240925T092434, end_date=20240925T092434
[2024-09-25T09:24:34.956+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 40 for task fetch_paginated_api_data (401 Client Error: Unauthorized for url: http://34.124.138.144:8000/api/common/authentication; 1045)
[2024-09-25T09:24:34.996+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-09-25T09:24:35.017+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
